### ISSUE TITLE
Error: NOT_RECEIVED when initializing contract

### ISSUE THREAD

**Issue by lsbyerley** [0xs34n/starknet.js#163]
Hello, following the example in the docs for deploying and creating an account contract, the initialize function returns a `NOT_RECEIVED` transaction hash

```js
const compiledArgentAccount = json.parse(
  fs.readFileSync("./ArgentAccount.json").toString("ascii")
);
const accountResponse = await defaultProvider.deployContract({
  contract: compiledArgentAccount,
  addressSalt: starkKeyPub,
});

await defaultProvider.waitForTransaction(accountResponse.transaction_hash);
const accountContract = new Contract(
  compiledArgentAccount.abi,
  accountResponse.address
);
const { transaction_hash: initializeTxHash } = await accountContract.initialize(
  starkKeyPub,
  "0"
);
await defaultProvider.waitForTransaction(initializeTxHash);

// intializeTxHash returns an error with NOT_RECEIVED
```

**Comment by yogh333** [comment]
Hello,
 Same issue reproduced on my side with 3.9.0 and starknet-devnet instance running....

**Comment by MilGard91** [comment]
Hi guys,
are you both using devnet, or this is happening on the testnet also?

**Comment by yogh333** [comment]
Hello,

 It's happening on devnet only on my side....

**Comment by MilGard91** [comment]
@yogh333 This should be working now on devnet, after the latest update. 

@lsbyerley We have the tests that are using the defaultProvider and that does the same invocation and it's working. Maybe the network was overloaded. You can check our test [here](https://github.com/0xs34n/starknet.js/blob/f9eeee37a18e454011ac3720bd0f4fdafb470c59/__tests__/account.test.ts#L22)

**Comment by yogh333** [comment]
@MilGard91 I have updated starknet-devnet to `0.1.20` and even ArgentAccount deployment fails now with `connect ECONNREFUSED 127.0.0.1:5001` error....

**Comment by MilGard91** [comment]
@yogh333 ok I will forward this to devnet team

**Comment by lsbyerley** [comment]
@MilGard91 i created a gist of my code.. can you spot anything wrong? I am still getting the NOT_RECEIVED error:

https://gist.github.com/lsbyerley/ddfa56d94ab8a850eb2257797955790d

I did notice the argent-x wallet uses `provider.invokeFunction()` as opposed to calling initialize function from the contract class `accountContract.initialize()` https://github.com/argentlabs/argent-x/blob/de0af196a4bd2c7f46748a666dd0ba972ce7f723/packages/extension/src/background/wallet.ts#L146

**Comment by lsbyerley** [comment]
@MilGard91 thanks, i believe my problem is resolved now!
